- name: Install static-web-server
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-static-web-server.sh') }}"
  environment:
    STATIC_WEB_SERVER_VERSION: "{{ static_web_server_version }}"
  register: static_web_server_result
  changed_when: "'ANSIBLE CHANGED NO' not in static_web_server_result.stdout_lines"
