- name: Install yq
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-yq.sh') }}"
  environment:
    YQ_VERSION: "{{ yq_version }}"
  register: yq_result
  changed_when: "'ANSIBLE CHANGED NO' not in yq_result.stdout_lines"
