- name: Install yq
  args:
    executable: /bin/bash
  shell: "{{ lookup('file', 'install-yq.sh') }}"
  environment:
    YQ_VERSION: "{{ yq_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
