# dns server listening address.
# NB this address will be assigned to the created dns0 bridge.
# NB this address should be used by the local virtual machines and
#    containers.
dns_local_dns_server: 10.53.53.53

dns_dns_servers:
  # delegate to the Cloudflare/APNIC Public DNS IP addresses.
  # see https://1.1.1.1
  - 1.1.1.1
  - 1.0.0.1
  # delegate to the Google Public DNS IP addresses.
  # see https://8.8.8.8
  # - 8.8.8.8
  # - 8.8.4.4

# system-networkd log level.
# NB set to debug to troubleshoot.
# NB set to null to unset the log level.
# NB to see the status execute: networkctl status dns0 #--json=short
# see https://wiki.ubuntu.com/DebuggingSystemd
# see https://wiki.archlinux.org/title/systemd-networkd
dns_system_networkd_log_level: null
