- name: Install argocd
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-argocd.sh') }}"
  environment:
    ARGOCD_VERSION: "{{ argocd_client_version }}"
  register: argocd_client_result
  changed_when: "'ANSIBLE CHANGED NO' not in argocd_client_result.stdout_lines"

- name: Install argocd bash completion
  block:
    - name: Get argocd bash completion
      ansible.builtin.command: argocd completion bash
      register: argocd_client_bash_completion
      changed_when: false
    - name: Install argocd bash completion
      ansible.builtin.copy:
        content: "{{ argocd_client_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/argocd
        mode: 0444
