- name: Install zig
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-zig.sh') }}"
  environment:
    ZIG_VERSION: "{{ zig_version }}"
  register: zig_result
  changed_when: "'ANSIBLE CHANGED NO' not in zig_result.stdout_lines"

- name: Add zig to PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/zig.sh
    content: |
      export PATH="$PATH:/opt/zig"
    mode: 0444
