- name: Show Helm Releases
  block:
    - name: Get Helm Releases
      ansible.builtin.command: helm ls -A
      register: helm_releases
      changed_when: false
    - name: Show Helm Releases
      ansible.builtin.debug:
        var: helm_releases.stdout

- name: Show Kubernetes Ingresses
  block:
    - name: Get Kubernetes Ingresses
      ansible.builtin.command: kubectl get -A ingress
      register: kubernetes_ingresses
      changed_when: false
    - name: Show Kubernetes Ingresses
      ansible.builtin.debug:
        var: kubernetes_ingresses.stdout
