- name: Install kind
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-kind.sh') }}"
  environment:
    KIND_VERSION: "{{ kind_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Install kind bash completion
  block:
    - name: Get kind bash completion
      ansible.builtin.command: kind completion bash
      register: bash_completion
      changed_when: false
    - name: Install kind bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/kind
        mode: 0444
