- name: Bump the inotify resource limits
  # NB this prevents the "too many open files" errors.
  # see https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files
  block:
    - name: Configure the inotify resource limits
      ansible.builtin.copy:
        content: |
          fs.inotify.max_user_watches = 524288
          fs.inotify.max_user_instances = 512
        dest: /etc/sysctl.d/20-inotify.conf
        mode: 0644
      register: kind_result
    - name: Set the inotify resource limits
      ansible.builtin.command: sysctl -p /etc/sysctl.d/20-inotify.conf
      when: kind_result.changed
      changed_when: kind_result.changed

- name: Install kind
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-kind.sh') }}"
  environment:
    KIND_VERSION: "{{ kind_version }}"
  register: kind_result
  changed_when: "'ANSIBLE CHANGED NO' not in kind_result.stdout_lines"

- name: Install kind bash completion
  block:
    - name: Get kind bash completion
      ansible.builtin.command: kind completion bash
      register: kind_bash_completion
      changed_when: false
    - name: Install kind bash completion
      ansible.builtin.copy:
        content: "{{ kind_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/kind
        mode: 0444
