# install kubernetes.
- name: Install kind
  ansible.builtin.include_tasks: kind.yml
- name: Install dependencies
  ansible.builtin.include_tasks: dependencies.yml
- name: Install Kubernetes
  become: true
  become_user: '{{ kind_provision_username }}'
  block:
    - name: Install helm-diff
      ansible.builtin.include_tasks: helm-diff.yml
    - name: Install the k8s cluster
      ansible.builtin.include_tasks: cluster.yml
    - name: Install MetalLB
      ansible.builtin.include_tasks: metallb.yml
    - name: Install cert-manager
      ansible.builtin.include_tasks: cert-manager.yml
    - name: Install trust-manager
      ansible.builtin.include_tasks: trust-manager.yml
    - name: Install reloader
      ansible.builtin.include_tasks: reloader.yml
    - name: Install Traefik
      ansible.builtin.include_tasks: traefik.yml
    - name: Install external-dns
      ansible.builtin.include_tasks: external-dns.yml
    - name: Install kubernetes-dashboard
      ansible.builtin.include_tasks: kubernetes-dashboard.yml
    - name: Configure the host
      ansible.builtin.include_tasks: host.yml
- name: Configure the host DNS
  ansible.builtin.include_tasks: dns.yml

# install applications.
- name: Install Applications
  become: true
  become_user: '{{ kind_provision_username }}'
  block:
    - name: Install PostgreSQL
      ansible.builtin.include_tasks: postgresql.yml
    - name: Install pgAdmin
      ansible.builtin.include_tasks: pgadmin.yml
    - name: Show information
      ansible.builtin.include_tasks: info.yml
