# install kubernetes.
- include_tasks: kind.yml
- include_tasks: dependencies.yml
- name: Install Kubernetes
  become: true
  become_user: '{{ provision_username }}'
  block:
    - include_tasks: helm-diff.yml
    - include_tasks: cluster.yml
    - include_tasks: metallb.yml
    - include_tasks: cert-manager.yml
    - include_tasks: traefik.yml
    - include_tasks: external-dns.yml
    - include_tasks: kubernetes-dashboard.yml
    - include_tasks: host.yml
- include_tasks: dns.yml

# install applications.
- name: Install Applications
  become: true
  become_user: '{{ provision_username }}'
  block:
    - include_tasks: yugabytedb.yml
    - include_tasks: pgadmin.yml
    - include_tasks: info.yml
