# see https://artifacthub.io/packages/helm/bitnami/postgresql
# see https://github.com/bitnami/charts/tree/main/bitnami/postgresql
# try helm status -n postgresql postgresql
# try kubectl -n postgresql get events
# try kubectl exec -n postgresql -it postgresql-0 -- bash
# try kubectl exec -n postgresql -it postgresql-0 -- env PGPASSWORD=postgres psql --host=postgresql --username=postgres --port=5432
# NB to completely delete postgresql execute:
#     helm uninstall -n postgresql postgresql
#     kubectl delete namespace postgresql # this will also delete the persistent volumes.

- name: Add bitnami repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Install postgresql
  kubernetes.core.helm:
    release_namespace: postgresql
    name: postgresql
    chart_ref: bitnami/postgresql
    chart_version: '{{ kind_postgresql_chart_version }}'
    create_namespace: true
    update_repo_cache: true
    wait: true
    values:
      auth:
        postgresPassword: postgres
