# see https://artifacthub.io/packages/helm/yugabyte/yugabyte
# see https://github.com/yugabyte/yugabyte-db/tree/master/cloud/kubernetes
# see https://download.yugabyte.com/#kubernetes
# see https://docs.yugabyte.com/stable/deploy/kubernetes/
# see https://docs.yugabyte.com/stable/architecture/
# see https://docs.yugabyte.com/stable/architecture/concepts/universe/
# see https://docs.yugabyte.com/stable/architecture/concepts/yb-master/
# see https://docs.yugabyte.com/stable/architecture/concepts/yb-tserver/
# try helm status -n yugabytedb yugabytedb
# try kubectl -n yugabytedb get events
# try kubectl exec -n yugabytedb -it yb-tserver-0 -- bash
# try kubectl exec -n yugabytedb -it yb-tserver-0 -- ysqlsh
# NB to completly delete yugabytedb execute:
#     helm uninstall -n yugabytedb yugabytedb
#     kubectl delete namespace yugabytedb # this will also delete the persistent volumes.

- name: Add yugabytedb repository
  kubernetes.core.helm_repository:
    name: yugabytedb
    repo_url: https://charts.yugabyte.com

- name: Install yugabytedb
  kubernetes.core.helm:
    release_namespace: yugabytedb
    name: yugabytedb
    chart_ref: yugabytedb/yugabyte
    chart_version: '{{ yugabytedb_chart_version }}'
    create_namespace: true
    update_repo_cache: true
    values:
      enableLoadBalancer: false # instead we use ingress.
      replicas:
        master: 1
        tserver: 1
      partition:
        master: 0
        tserver: 0
      storage:
        ephemeral: false
        master:
          count: 1
          size: 2Gi
          storageClass: standard
        tserver:
          count: 1
          size: 2Gi
          storageClass: standard
      resource:
        master:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
        tserver:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi

- name: Create yb-master-ui Ingress Certificate
  kubernetes.core.k8s:
    namespace: yugabytedb
    definition:
      # see https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: yb-master-ui
      spec:
        subject:
          organizations:
            - '{{ cluster_name }}.{{ cluster_domain }}'
          organizationalUnits:
            - Kubernetes
        commonName: YugabyteDB Master UI
        dnsNames:
          - yb-master-ui.{{ cluster_name }}.{{ cluster_domain }}
        duration: 1h # NB this is so low for testing purposes.
        privateKey:
          algorithm: ECDSA # NB Ed25519 is not yet supported by chrome 93 or firefox 91.
          size: 256
        secretName: yb-master-ui-tls
        issuerRef:
          kind: ClusterIssuer
          name: ingress

- name: Create the yb-master-ui Ingress
  kubernetes.core.k8s:
    namespace: yugabytedb
    definition:
      # see https://kubernetes.io/docs/concepts/services-networking/ingress/
      # see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#ingress-v1-networking-k8s-io
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: yb-master-ui
      spec:
        rules:
          - host: yb-master-ui.{{ cluster_name }}.{{ cluster_domain }}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: yb-masters
                      port:
                        name: http-ui
        tls:
          - secretName: yb-master-ui-tls

- name: Create yb-tserver-ui Ingress Certificate
  kubernetes.core.k8s:
    namespace: yugabytedb
    definition:
      # see https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: yb-tserver-ui
      spec:
        subject:
          organizations:
            - '{{ cluster_name }}.{{ cluster_domain }}'
          organizationalUnits:
            - Kubernetes
        commonName: YugabyteDB TServer UI
        dnsNames:
          - yb-tserver-ui.{{ cluster_name }}.{{ cluster_domain }}
        duration: 1h # NB this is so low for testing purposes.
        privateKey:
          algorithm: ECDSA # NB Ed25519 is not yet supported by chrome 93 or firefox 91.
          size: 256
        secretName: yb-tserver-ui-tls
        issuerRef:
          kind: ClusterIssuer
          name: ingress

- name: Create the yb-tserver-ui Ingress
  kubernetes.core.k8s:
    namespace: yugabytedb
    definition:
      # see https://kubernetes.io/docs/concepts/services-networking/ingress/
      # see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#ingress-v1-networking-k8s-io
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: yb-tserver-ui
      spec:
        rules:
          - host: yb-tserver-ui.{{ cluster_name }}.{{ cluster_domain }}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: yb-tservers
                      port:
                        name: http-ui
        tls:
          - secretName: yb-tserver-ui-tls
