- name: Install {{ item }}
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-regclient.sh') }}"
  environment:
    REGCLIENT_NAME: "{{ item }}"
    REGCLIENT_VERSION: "{{ regclient_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Install {{ item }} bash completion
  block:
    - name: Get {{ item }} bash completion
      ansible.builtin.command: "{{ item }} completion bash"
      register: bash_completion
      changed_when: false
    - name: Install {{ item }} bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/{{ item }}
        mode: 0444
