- name: Install rust
  become_user: '{{ ansible_user }}'
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-rust.sh') }}"
  environment:
    RUST_VERSION: "{{ rust_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
