- name: Install rust
  become_user: '{{ ansible_user }}'
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-rust.sh') }}"
  environment:
    RUST_VERSION: "{{ rust_version }}"
  register: rust_result
  changed_when: "'ANSIBLE CHANGED NO' not in rust_result.stdout_lines"
