- name: Install talosctl
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install.sh') }}"
  environment:
    TALOSCTL_VERSION: "{{ talosctl_version }}"
  register: talosctl_result
  changed_when: "'ANSIBLE CHANGED NO' not in talosctl_result.stdout_lines"

- name: Install talosctl bash completion
  block:
    - name: Get talosctl bash completion
      ansible.builtin.command: talosctl completion bash
      register: talosctl_bash_completion
      changed_when: false
    - name: Install talosctl bash completion
      ansible.builtin.copy:
        content: "{{ talosctl_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/talosctl
        mode: 0444
