- name: Install talosctl
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install.sh') }}"
  environment:
    TALOSCTL_VERSION: "{{ talosctl_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Install talosctl bash completion
  block:
    - name: Get talosctl bash completion
      ansible.builtin.command: talosctl completion bash
      register: bash_completion
      changed_when: false
    - name: Install talosctl bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/talosctl
        mode: 0444
