- name: Install terramate
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-terramate.sh') }}"
  environment:
    TERRAMATE_VERSION: "{{ terramate_version }}"
  register: terramate_result
  changed_when: "'ANSIBLE CHANGED NO' not in terramate_result.stdout_lines"

- name: Install terramate bash completion
  ansible.builtin.copy:
    content: |
      complete -C /usr/local/bin/terramate terramate
    dest: /usr/share/bash-completion/completions/terramate
    mode: 0444
