- name: Install lms
  ansible.builtin.apt:
    deb: https://github.com/rgl/lms-binaries/releases/download/{{ lms_binaries_version }}/lms-{{ lms_version }}-ubuntu-{{ ansible_distribution_version }}.deb # yamllint disable-line rule:line-length
