collections:
  # see https://galaxy.ansible.com/ansible/posix
  - name: ansible.posix
    version: 2.0.0
  # see https://galaxy.ansible.com/ansible/utils
  - name: ansible.utils
    version: 5.1.2
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 10.2.0
  # see https://galaxy.ansible.com/community/docker
  - name: community.docker
    version: 4.3.1
  # see https://galaxy.ansible.com/kubernetes/core
  - name: kubernetes.core
    version: 5.0.0
