collections:
  # see https://galaxy.ansible.com/ansible/posix
  - name: ansible.posix
    version: 1.6.0
  # see https://galaxy.ansible.com/ansible/utils
  - name: ansible.utils
    version: 5.1.1
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 9.4.0
  # see https://galaxy.ansible.com/community/docker
  - name: community.docker
    version: 3.12.2
  # see https://galaxy.ansible.com/kubernetes/core
  - name: kubernetes.core
    version: 5.0.0
