collections:
  # see https://galaxy.ansible.com/ansible/posix
  - name: ansible.posix
    version: 1.5.4
  # see https://galaxy.ansible.com/ansible/utils
  - name: ansible.utils
    version: 4.1.0
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 8.6.0
  # see https://galaxy.ansible.com/community/docker
  - name: community.docker
    version: 3.9.0
  # see https://galaxy.ansible.com/kubernetes/core
  - name: kubernetes.core
    version: 3.1.0
