collections:
  # see https://galaxy.ansible.com/ansible/posix
  - name: ansible.posix
    version: 1.5.2
  # see https://galaxy.ansible.com/ansible/utils
  - name: ansible.utils
    version: 2.10.1
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 7.0.0
  # see https://galaxy.ansible.com/community/docker
  - name: community.docker
    version: 3.4.5
  # see https://galaxy.ansible.com/kubernetes/core
  - name: kubernetes.core
    version: 2.4.0
