collections:
  # see https://galaxy.ansible.com/ansible/posix
  - name: ansible.posix
    version: 2.1.0
  # see https://galaxy.ansible.com/ansible/utils
  - name: ansible.utils
    version: 6.0.0
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 11.2.1
  # see https://galaxy.ansible.com/community/docker
  - name: community.docker
    version: 4.7.0
  # see https://galaxy.ansible.com/kubernetes/core
  - name: kubernetes.core
    version: 6.1.0
