# see https://code.visualstudio.com/docs/setup/linux

- name: Download the microsoft apt key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.com.asc
    mode: 0444
    force: true

- name: Add the Visual Studio Code repository
  ansible.builtin.apt_repository:
    # see https://wiki.debian.org/DebianRepository/Format
    # see https://packages.microsoft.com/repos/code/dists/stable/Release
    # see https://packages.microsoft.com/repos/code/dists/stable/main/binary-amd64/Packages
    repo: >
      deb
      [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.com.asc]
      https://packages.microsoft.com/repos/code
      stable
      main
    state: present

- name: Install Visual Studio Code
  ansible.builtin.apt:
    name: code

- name: Configure Visual Studio Code
  become: true
  become_user: '{{ ansible_user }}'
  block:
    - name: Create the Settings Directory
      ansible.builtin.file:
        name: ~/.config/Code/User
        state: directory
        mode: 0755
    - name: Read Settings
      ansible.builtin.shell:
        executable: /bin/bash
        # see https://code.visualstudio.com/docs/getstarted/settings#_settingsjson
        cmd: |
          set -euxo pipefail
          f=~/.config/Code/User/settings.json
          ([ -f "$f" ] && cat "$f" || echo '{}') | yq \
            --output-format json \
            --prettyPrint \
            --indent 4 \
            e \
              '
                ."telemetry.telemetryLevel" = "off"
              | ."redhat.telemetry.enabled" = false
              | ."[svelte]" = {"editor.defaultFormatter":"svelte.svelte-vscode"}
              | ."files.associations"."*.tm.hcl" = "terramate"
              '
      register: settings
      changed_when: false
    - name: Write Settings
      ansible.builtin.copy:
        dest: ~/.config/Code/User/settings.json
        content: '{{ settings.stdout }}'
        mode: 0644

- name: Install Zig Extensions dependencies
  ansible.builtin.apt:
    name:
      - gdb

- name: Install code extension
  become: true
  become_user: '{{ ansible_user }}'
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-code-extension.sh') }}"
  environment:
    CODE_EXTENSION_NAME: "{{ item }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
  loop:
    # XML.
    # see https://github.com/DotJoshJohnson/vscode-xml
    # see https://marketplace.visualstudio.com/items?itemName=dotjoshjohnson.xml
    - dotjoshjohnson.xml
    # Go language.
    # see https://github.com/golang/vscode-go
    # see https://marketplace.visualstudio.com/items?itemName=golang.Go
    - golang.go
    # HCL.
    # see https://github.com/hashicorp/vscode-hcl
    # see https://marketplace.visualstudio.com/items?itemName=hashicorp.hcl
    - hashicorp.hcl
    # Terraform.
    # see https://github.com/hashicorp/vscode-terraform
    # see https://marketplace.visualstudio.com/items?itemName=hashicorp.terraform
    - hashicorp.terraform
    # Terramate.
    # see https://github.com/terramate-io/vscode-terramate
    # see https://marketplace.visualstudio.com/items?itemName=mineiros.terramate
    - mineiros.terramate
    # Docker.
    # see https://github.com/microsoft/vscode-docker
    # see https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker
    - ms-azuretools.vscode-docker
    # C# language.
    # see https://github.com/dotnet/vscode-csharp
    # see https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
    - ms-dotnettools.csharp
    # C# Dev Kit.
    # see https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit
    - ms-dotnettools.csdevkit
    # Python language.
    # NB this depends on the pylance extension (which includes pyright).
    # NB this depends on the python debugger extension.
    # see https://github.com/Microsoft/vscode-python
    # see https://marketplace.visualstudio.com/items?itemName=ms-python.python
    - ms-python.python
    # Python code formatter.
    # see https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter
    - ms-python.black-formatter
    # Remote SSH.
    # see https://github.com/Microsoft/vscode-remote-release
    # see https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh
    # PowerShell language.
    # see https://github.com/PowerShell/vscode-powershell
    # see https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell
    - ms-vscode.powershell
    # Makefile Tools.
    # see https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools
    - ms-vscode.makefile-tools
    # see https://bun.sh/guides/runtime/vscode-debugger
    # see https://marketplace.visualstudio.com/items?itemName=oven.bun-vscode
    - oven.bun-vscode
    # Jinja Template Highlighting.
    # see https://github.com/samuelcolvin/jinjahtml-vscode
    # see https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml
    # NB be aware of https://github.com/microsoft/vscode/issues/49210
    - samuelcolvin.jinjahtml
    # Spell checker.
    # see https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker
    # see https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-portuguese
    - streetsidesoftware.code-spell-checker-portuguese
    # Deno support.
    # see https://github.com/denoland/vscode_deno
    # see https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno
    - denoland.vscode-deno
    # Rust language support.
    # see https://github.com/rust-lang/rust-analyzer
    # see https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer
    - rust-lang.rust-analyzer
    # Zig Language support.
    # see https://github.com/ziglang/vscode-zig
    # see https://marketplace.visualstudio.com/items?itemName=ziglang.vscode-zig
    - ziglang.vscode-zig
    # Zig Language Debugging/Testing support.
    # see https://github.com/ianic/zig-language-extras
    # see https://marketplace.visualstudio.com/items?itemName=ianic.zig-language-extras
    - ianic.zig-language-extras
    # Svelte language support.
    # see https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode
    - svelte.svelte-vscode
    # GitHub Actions.
    # see https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions
    - github.vscode-github-actions
    # Playwright Test.
    # see https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright
    - ms-playwright.playwright
    # PDF Viewer.
    # see https://github.com/tomoki1207/vscode-pdfviewer
    # see https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf
    - tomoki1207.pdf
    # ANSI support.
    # see https://github.com/iliazeus/vscode-ansi
    # see https://marketplace.visualstudio.com/items?itemName=iliazeus.vscode-ansi
    - iliazeus.vscode-ansi
    # Mermaid support.
    # see https://github.com/Mermaid-Chart/vscode-mermaid-preview
    # see https://marketplace.visualstudio.com/items?itemName=vstirbu.vscode-mermaid-preview
    - vstirbu.vscode-mermaid-preview

- name: Set Visual Studio Code as the text/plain default editor
  become: true
  become_user: '{{ ansible_user }}'
  community.general.xdg_mime:
    mime_types: text/plain
    handler: code.desktop
