# see https://code.visualstudio.com/docs/setup/linux

- name: Add the Visual Studio Code repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/repos/code stable main
    state: present

- name: Install Visual Studio Code
  ansible.builtin.apt:
    name: code

- name: Configure Visual Studio Code
  become_user: '{{ ansible_user }}'
  block:
    - name: Read Settings
      args:
        executable: /bin/bash
      ansible.builtin.shell: |
        f=~/.config/Code/User/settings.json
        ([ -f "$f" ] && cat "$f" || echo '{}') | yq \
          --output-format json \
          --prettyPrint \
          --indent 4 \
          e \
            '
              ."telemetry.telemetryLevel" = "off"
            | ."redhat.telemetry.enabled" = false
            '
      register: settings
      changed_when: false
    - name: Write Settings
      ansible.builtin.copy:
        dest: ~/.config/Code/User/settings.json
        content: '{{ settings.stdout }}'
        mode: 0644

- name: Install code plugin
  become_user: '{{ ansible_user }}'
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-code-plugin.sh') }}"
  environment:
    CODE_PLUGIN_NAME: "{{ item }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
  loop:
    - dotjoshjohnson.xml
    - golang.go
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-dotnettools.csharp
    - ms-python.python
    - ms-vscode-remote.remote-ssh
    - ms-vscode.powershell

- name: Set Visual Studio Code as the text/plain default editor
  become_user: '{{ ansible_user }}'
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    set -euo pipefail
    expected='code.desktop'
    actual="$(xdg-mime query default text/plain)"
    if [ "$actual" == "$expected" ]; then
      echo 'ANSIBLE CHANGED NO'
    else
      xdg-mime default "$expected" text/plain
    fi
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
