# see https://code.visualstudio.com/docs/setup/linux

- name: Add the microsoft apt key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/keyrings/packages.microsoft.com.gpg

- name: Add the Visual Studio Code repository
  ansible.builtin.apt_repository:
    # see https://wiki.debian.org/DebianRepository/Format
    # see https://packages.microsoft.com/repos/code/dists/stable/Release
    # see https://packages.microsoft.com/repos/code/dists/stable/main/binary-amd64/Packages
    repo: >
      deb
      [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.com.gpg]
      https://packages.microsoft.com/repos/code
      stable
      main
    state: present

- name: Install Visual Studio Code
  ansible.builtin.apt:
    name: code

# NB the code debian package has some code to create this extraneous
#    vscode.list file, but it conflicts with the microsoft apt repository
#    that was created above, so it must be removed.
- name: Remove vscode.list
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/vscode.list
    state: absent

- name: Configure Visual Studio Code
  become_user: '{{ ansible_user }}'
  block:
    - name: Create the Settings Directory
      ansible.builtin.file:
        name: ~/.config/Code/User
        state: directory
        mode: 0755
    - name: Read Settings
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -euxo pipefail
          f=~/.config/Code/User/settings.json
          ([ -f "$f" ] && cat "$f" || echo '{}') | yq \
            --output-format json \
            --prettyPrint \
            --indent 4 \
            e \
              '
                ."telemetry.telemetryLevel" = "off"
              | ."redhat.telemetry.enabled" = false
              | ."[svelte]" = {"editor.defaultFormatter":"svelte.svelte-vscode"}
              '
      register: settings
      changed_when: false
    - name: Write Settings
      ansible.builtin.copy:
        dest: ~/.config/Code/User/settings.json
        content: '{{ settings.stdout }}'
        mode: 0644

- name: Install code extension
  become_user: '{{ ansible_user }}'
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-code-extension.sh') }}"
  environment:
    CODE_EXTENSION_NAME: "{{ item }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
  loop:
    - dotjoshjohnson.xml
    - golang.go
    - hashicorp.hcl
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-dotnettools.csharp
    - ms-python.python
    - ms-vscode-remote.remote-ssh
    - ms-vscode.powershell
    # Makefile Tools.
    # see https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools
    - ms-vscode.makefile-tools
    # see https://bun.sh/guides/runtime/vscode-debugger
    # see https://marketplace.visualstudio.com/items?itemName=oven.bun-vscode
    - oven.bun-vscode
    # Jinja Template Highlighting.
    # see https://github.com/samuelcolvin/jinjahtml-vscode
    # see https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml
    # NB be aware of https://github.com/microsoft/vscode/issues/49210
    - samuelcolvin.jinjahtml
    # Spell checker.
    # see https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker
    # Rust language support.
    # see https://github.com/rust-lang/rust-analyzer
    # see https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer
    - rust-lang.rust-analyzer
    # Svelte language support.
    # see https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode
    - svelte.svelte-vscode
    # GitHub Actions.
    # see https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions
    - github.vscode-github-actions

- name: Set Visual Studio Code as the text/plain default editor
  become_user: '{{ ansible_user }}'
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -euxo pipefail
      expected='code.desktop'
      actual="$(xdg-mime query default text/plain)"
      if [ "$actual" == "$expected" ]; then
        echo 'ANSIBLE CHANGED NO'
      else
        xdg-mime default "$expected" text/plain
      fi
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
