- name: Install minimal desktop
  apt:
    name: ubuntu-desktop-minimal
    install_recommends: true
  notify: reboot

# use the xorg backend because not all apps (e.g. xrdp) are ready for wayland.
- name: Use the Xorg backend
  block:
    - name: Disable Wayland
      community.general.ini_file:
        path: /etc/gdm3/custom.conf
        section: daemon
        option: WaylandEnable
        value: 'false'
        no_extra_spaces: true
    - name: Set the Default Session to Xorg
      # see /usr/share/xsessions/*.desktop
      community.general.ini_file:
        path: /etc/gdm3/custom.conf
        section: daemon
        option: DefaultSession
        value: ubuntu-xorg.desktop
        no_extra_spaces: true

# NB the same user cannot login locally and remotely at the same time. one of
#    the sessions will see a black screen. to logout a stuck session, you can
#    try with:
#       gnome-session-quit --logout --no-prompt
# NB see the logs at:
#       ~/.xorgxrdp.*.log
#       ~/.xsession-errors
- name: Install xrdp
  block:
    - apt:
        name: xrdp
    - name: Allow the xrdp user to read the machine ssl certificate keys
      user:
        name: xrdp
        groups: ssl-cert
        append: yes
    - name: Do not allow root login
      community.general.ini_file:
        path: /etc/xrdp/sesman.ini
        section: Security
        option: AllowRootLogin
        value: 'false'
        no_extra_spaces: true
    - name: Install the colord PolicyKit Local Authority Policy
      # see /usr/share/polkit-1/actions/org.freedesktop.color.policy
      # see pkla-check-authorization(8)
      # see xRDP How to Fix the Infamous system crash popups at http://c-nergy.be/blog/?p=12043
      # see xRDP Easy install xRDP on Ubuntu at https://c-nergy.be/blog/?p=15733
      # see xRDP installer script at https://c-nergy.be/products.html
      copy:
        src: 45-colord.pkla
        dest: /etc/polkit-1/localauthority/50-local.d/45-colord.pkla
    - name: Configure Session Variables
      # see Fixing Theme and Extensions at http://c-nergy.be/blog/?p=12043
      copy:
        dest: /etc/X11/Xsession.d/00xrdp
        content: |
          if [ -z "$XRDP_SESSION" ]; then
            return 0
          fi
          export GNOME_SHELL_SESSION_MODE=ubuntu
          export XDG_CURRENT_DESKTOP=ubuntu:GNOME
          export XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
  notify: restart xrdp

- name: Disable Gnome Initial Setup
  # see https://gitlab.gnome.org/GNOME/gnome-initial-setup
  apt:
    name: gnome-initial-setup
    state: absent

- name: Install community.general.dconf module dependencies
  apt:
    name: python3-psutil

- name: Install gnome-shell-extension-manager
  apt:
    name: gnome-shell-extension-manager

# NB you can get the current value with:
#       dconf read /org/gnome/shell/extensions/ding/show-trash
# see /usr/share/glib-2.0/schemas/org.gnome.shell.extensions.ding.gschema.xml
- name: Show the trash icon in the desktop
  become: false
  community.general.dconf:
    key: /org/gnome/shell/extensions/ding/show-trash
    value: 'true'

# NB you can get the current value with:
#       dconf read /org/gnome/shell/extensions/dash-to-dock/click-action
# See /usr/share/glib-2.0/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
- name: Enable click to minimize
  become: false
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/click-action
    value: "'minimize'"

# NB you can get the current value with:
#       dconf read /org/gnome/desktop/interface/color-scheme
# See /usr/share/glib-2.0/schemas/org.gnome.desktop.interface.gschema.xml
- name: Use the dark color scheme
  become: false
  community.general.dconf:
    key: /org/gnome/desktop/interface/color-scheme
    value: "'prefer-dark'"
