- name: Install minimal desktop
  ansible.builtin.apt:
    name: ubuntu-desktop-minimal
    install_recommends: true
  notify: Reboot

- include_tasks: xrdp.yml

- name: Disable Gnome Initial Setup
  # see https://gitlab.gnome.org/GNOME/gnome-initial-setup
  ansible.builtin.apt:
    name: gnome-initial-setup
    state: absent

- name: Install community.general.dconf module dependencies
  ansible.builtin.apt:
    name: python3-psutil

- name: Install gnome-shell-extension-manager
  # see https://github.com/mjakeman/extension-manager
  ansible.builtin.apt:
    name: gnome-shell-extension-manager

# NB you can get the current value with:
#       dconf read /org/gnome/shell/extensions/ding/show-trash
# see /usr/share/glib-2.0/schemas/org.gnome.shell.extensions.ding.gschema.xml
- name: Show the trash icon in the desktop
  become: false
  community.general.dconf:
    key: /org/gnome/shell/extensions/ding/show-trash
    value: 'true'

# NB you can get the current value with:
#       dconf read /org/gnome/shell/extensions/dash-to-dock/click-action
# See /usr/share/glib-2.0/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
- name: Enable click to minimize
  become: false
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/click-action
    value: "'minimize'"

# NB you can get the current value with:
#       dconf read /org/gnome/desktop/interface/enable-animations
# See /usr/share/glib-2.0/schemas/org.gnome.desktop.interface.gschema.xml
- name: Disable animations
  become: false
  community.general.dconf:
    key: /org/gnome/desktop/interface/enable-animations
    value: 'false'

# NB these settings were obtained in two steps:
#       1. dconf dump / >dconf.orig.ini
#       2. edit the appearance settings using the GUI
#          * apt-get install gnome-control-center gnome-tweaks dconf-editor
#       3. dconf dump / >dconf.ini
#       4. diff -u dconf.orig.ini dconf.ini
# See /usr/share/glib-2.0/schemas/org.gnome.desktop.interface.gschema.xml
- name: Configure the theme
  become: false
  block:
    - name: Use the dark color scheme
      community.general.dconf:
        key: /org/gnome/desktop/interface/color-scheme
        value: "'prefer-dark'"
    - name: Set the GTK theme
      community.general.dconf:
        key: /org/gnome/desktop/interface/gtk-theme
        value: "'Yaru-olive-dark'"
    - name: Set the icon theme
      community.general.dconf:
        key: /org/gnome/desktop/interface/icon-theme
        value: "'Yaru-olive'"

- name: Configure the desktop background
  become: false
  block:
    - name: Set color-shading-type
      community.general.dconf:
        key: /org/gnome/desktop/background/color-shading-type
        value: "'solid'"
    - name: Set picture-options
      community.general.dconf:
        key: /org/gnome/desktop/background/picture-options
        value: "'zoom'"
    - name: Set picture-uri-dark
      community.general.dconf:
        key: /org/gnome/desktop/background/picture-uri-dark
        value: "'file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'"
    - name: Set primary-color
      community.general.dconf:
        key: /org/gnome/desktop/background/primary-color
        value: "'#000000'"
    - name: Set secondary-color
      community.general.dconf:
        key: /org/gnome/desktop/background/secondary-color
        value: "'#000000'"

- name: Configure the topbar
  become: false
  block:
    - name: Show the date
      community.general.dconf:
        key: /org/gnome/desktop/interface/clock-show-date
        value: 'true'
    - name: Show the weekday
      community.general.dconf:
        key: /org/gnome/desktop/interface/clock-show-weekday
        value: 'true'

- name: Install Dash to Panel
  become: false
  block:
    - name: Install Dash to Panel
      gnome_extension:
        # see https://extensions.gnome.org/extension/1160/dash-to-panel/
        # see https://github.com/home-sweet-gnome/dash-to-panel
        name: dash-to-panel@jderose9.github.com
    - name: Set Panel thickness
      community.general.dconf:
        key: /org/gnome/shell/extensions/dash-to-panel/panel-sizes
        value: "'{\"0\":32}'"
    - name: Set App icon margin
      community.general.dconf:
        key: /org/gnome/shell/extensions/dash-to-panel/appicon-margin
        value: '0'
    - name: Disable Ungroup applications
      community.general.dconf:
        key: /org/gnome/shell/extensions/dash-to-panel/group-apps
        value: 'false'
    - name: Disable Display running indicators on unfocused applications
      community.general.dconf:
        key: /org/gnome/shell/extensions/dash-to-panel/group-apps-underline-unfocused
        value: 'false'

- name: Set the user face picture
  block:
    # see /usr/share/pixmaps/faces
    # see /var/lib/AccountsService/users/$user
    # see /var/lib/AccountsService/icons/$user
    # see ~/.face
    # see https://help.gnome.org/admin/gdm/stable/overview.html.en#facebrowser
    # NB this is aka the user face/icon/avatar/picture.
    # NB because the gdm user must be able to read the face picture, and the
    #    user home directory does not have the required permissions, we've
    #    opted to set the image globally instead of in ~/.face.
    # NB the optimal image size is 96x96.
    - name: Set the user face picture
      ansible.builtin.copy:
        src: vagrant-face.png
        dest: "/usr/share/pixmaps/faces/{{ ansible_user }}"
        mode: 0444
    - name: Configure the user face picture
      community.general.ini_file:
        path: "/var/lib/AccountsService/users/{{ ansible_user }}"
        section: User
        option: Icon
        value: "/usr/share/pixmaps/faces/{{ ansible_user }}"
        no_extra_spaces: true
        mode: 0600
