# see https://www.google.com/linuxrepositories/
- name: Download the Google Chrome apt key
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/dl.google.com.chrome.asc
    mode: 0444
    force: true

- name: Add the Google Chrome repository
  ansible.builtin.apt_repository:
    # see https://wiki.debian.org/DebianRepository/Format
    # see Ubuntu Jammy 22.04: http://dl.google.com/linux/chrome/deb/dists/stable/Release
    # see Ubuntu Jammy 22.04: http://dl.google.com/linux/chrome/deb/dists/stable/main/binary-amd64/Packages
    repo: >
      deb
      [arch=amd64 signed-by=/etc/apt/keyrings/dl.google.com.chrome.asc]
      http://dl.google.com/linux/chrome/deb/
      stable
      main
    state: present

# e.g. prevent it from creating the /etc/apt/trusted.gpg.d/google-chrome.gpg file et al.
- name: Prevent the Google Chrome package from installing the Google repository
  ansible.builtin.copy:
    content: ''
    dest: /etc/default/google-chrome
    mode: 0444

# NB if you are having problems with google chrome, try executing it from the
#    command line with the --v=1 argument.
# NB if the log shows skia errors, try to delete your profile GPU cache
#    directory, which is normally at ~/.config/google-chrome/Default/GPUCache.
- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    # NB we have to use latest because there is only one version available
    #    at the repository.
    state: latest # noqa package-latest
