- name: Install httptoolkit
  ansible.builtin.apt:
    deb: https://github.com/httptoolkit/httptoolkit-desktop/releases/download/v{{ desktop_httptoolkit_version }}/HttpToolkit-{{ desktop_httptoolkit_version }}-{{ 'x64' if ansible_architecture == 'x86_64' else 'arm64' }}.deb # noqa yaml[line-length]
