- name: Install meld
  block:
    - name: Install meld
      ansible.builtin.apt:
        name: meld
        install_recommends: false
    # NB you must also edit the base role files/gitconfig file to include this one.
    - name: Configure git to use meld
      ansible.builtin.copy:
        src: meld.gitconfig
        dest: /etc/gitconfig.d/meld.gitconfig
        mode: 0444
