- name: Install meld
  block:
    - name: Install meld
      ansible.builtin.apt:
        name: meld
        install_recommends: false
    - name: Configure git to use meld
      ansible.builtin.copy:
        src: meld.gitconfig
        # NB you must include this file from the roles/base/files/gitconfig file.
        dest: /etc/gitconfig.d/meld.gitconfig
        mode: 0444
