# NB to configure netbird, you still need to connect from the ui or
#    execute sudo netbird up.
# see https://github.com/netbirdio/netbird
# see https://app.netbird.io/add-peer

- name: Add the Wiretrustee apt key
  ansible.builtin.apt_key:
    url: https://pkgs.wiretrustee.com/debian/public.key
    keyring: /etc/apt/keyrings/pkgs.wiretrustee.com.gpg

- name: Add the Wiretrustee repository
  ansible.builtin.apt_repository:
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/pkgs.wiretrustee.com.gpg]
      https://pkgs.wiretrustee.com/debian
      stable
      main

- name: Install NetBird
  block:
    - name: Install NetBird
      ansible.builtin.apt:
        name:
          - netbird={{ netbird_version }}
          - netbird-ui={{ netbird_version }}
        allow_change_held_packages: true
    - name: Pin netbird
      ansible.builtin.dpkg_selections:
        name: '{{ item }}'
        selection: hold
      loop:
        - netbird
        - netbird-ui

- name: Configure NetBird
  netbird_config:
    iface_black_list_include:
      - dns0

- name: Install the WireGuard tools
  # NB this is not strictly required, but it allows us to use the wg
  #    command to further inspect things.
  ansible.builtin.apt:
    name: wireguard-tools
