# NB to configure netbird, you still need to connect from the ui or
#    execute sudo netbird up.
# see https://github.com/netbirdio/netbird
# see https://app.netbird.io/add-peer

- name: Add the NetBird apt key
  ansible.builtin.apt_key:
    url: https://pkgs.netbird.io/debian/public.key
    keyring: /etc/apt/keyrings/pkgs.netbird.io.gpg

- name: Add the NetBird repository
  ansible.builtin.apt_repository:
    # see https://wiki.debian.org/DebianRepository/Format
    # see https://pkgs.netbird.io/debian/dists/stable/InRelease
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/pkgs.netbird.io.gpg]
      https://pkgs.netbird.io/debian
      stable
      main

- name: Install NetBird
  block:
    - name: Install NetBird
      ansible.builtin.apt:
        name: netbird={{ desktop_netbird_version }}
        allow_change_held_packages: true
      notify: Restart netbird
    - name: Install NetBird UI
      ansible.builtin.apt:
        name: netbird-ui={{ desktop_netbird_version }}
        allow_change_held_packages: true
    - name: Pin netbird
      ansible.builtin.dpkg_selections:
        name: '{{ item }}'
        selection: hold
      loop:
        - netbird
        - netbird-ui

- name: Configure NetBird
  netbird_config:
    iface_black_list_include:
      - dns0

- name: Delegate the netbird.cloud DNS domain to the local NetBird dns server
  ansible.builtin.copy:
    # set the dns server to the local netbird peer ip address.
    content: |
      server=/netbird.cloud/{{ ansible_wt0.ipv4.address }}#53
    dest: /etc/dnsmasq.d/netbird.cloud.conf
    mode: 0444
  when: ansible_wt0 is defined and ansible_wt0.ipv4.address
  notify: Restart dnsmasq

- name: Install the WireGuard tools
  # NB this is not strictly required, but it allows us to use the wg
  #    command to further inspect things.
  ansible.builtin.apt:
    name: wireguard-tools
