# see https://github.com/raspberrypi/rpi-imager/releases

- name: Uninstall rpi-imager apt package
  ansible.builtin.apt:
    name: rpi-imager
    state: absent
    purge: true
    allow_change_held_packages: true

- name: Install rpi-imager
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-rpi-imager.sh') }}"
  environment:
    RPI_IMAGER_VERSION: "{{ desktop_rpi_imager_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
