# see https://www.sublimemerge.com/docs/linux_repositories

- name: Add the sublimehq-archive-keyring apt key
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    keyring: /etc/apt/keyrings/download.sublimetext.com.gpg

- name: Add the sublimetext repository
  ansible.builtin.apt_repository:
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/download.sublimetext.com.gpg]
      https://download.sublimetext.com/
      apt/stable/

- name: Install Sublime Merge
  ansible.builtin.apt:
    name: sublime-merge
