# see https://www.sublimemerge.com/docs/linux_repositories

- name: Download the sublimehq-archive-keyring apt key
  ansible.builtin.get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /etc/apt/keyrings/download.sublimetext.com.asc
    mode: 0444
    force: true

- name: Add the sublimetext repository
  ansible.builtin.apt_repository:
    # see https://wiki.debian.org/DebianRepository/Format
    # see https://download.sublimetext.com/apt/stable/Release
    # see https://download.sublimetext.com/apt/stable/Packages
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/download.sublimetext.com.asc]
      https://download.sublimetext.com/
      apt/stable/

- name: Install Sublime Merge
  ansible.builtin.apt:
    name: sublime-merge
