- name: Use the Wayland backend
  when: desktop_use_wayland
  block:
    - name: Enable Wayland
      community.general.ini_file:
        path: /etc/gdm3/custom.conf
        section: daemon
        option: WaylandEnable
        value: 'true'
        no_extra_spaces: true
        mode: 0444
    - name: Set the Default Session to Wayland
      # see /usr/share/xsessions/*.desktop
      community.general.ini_file:
        path: /etc/gdm3/custom.conf
        section: daemon
        option: DefaultSession
        value: ubuntu.desktop
        no_extra_spaces: true
        mode: 0444

# use the xorg backend because not all apps (e.g. xrdp) are ready for wayland.
- name: Use the Xorg backend
  when: not desktop_use_wayland
  block:
    - name: Disable Wayland
      community.general.ini_file:
        path: /etc/gdm3/custom.conf
        section: daemon
        option: WaylandEnable
        value: 'false'
        no_extra_spaces: true
        mode: 0444
    - name: Set the Default Session to Xorg
      # see /usr/share/xsessions/*.desktop
      community.general.ini_file:
        path: /etc/gdm3/custom.conf
        section: daemon
        option: DefaultSession
        value: ubuntu-xorg.desktop
        no_extra_spaces: true
        mode: 0444

# NB the same user cannot login locally and remotely at the same time. one of
#    the sessions will see a black screen. to logout a stuck session, you can
#    try with:
#       gnome-session-quit --logout --no-prompt
# NB see the logs at:
#       ~/.xorgxrdp.*.log
#       ~/.xsession-errors
- name: Install xrdp
  notify: Restart xrdp
  block:
    - name: Install xrdp
      ansible.builtin.apt:
        name:
          - xrdp
          - xorgxrdp
    - name: Allow the xrdp user to read the machine ssl certificate keys
      ansible.builtin.user:
        name: xrdp
        groups: ssl-cert
        append: true
    - name: Do not allow root login
      community.general.ini_file:
        path: /etc/xrdp/sesman.ini
        section: Security
        option: AllowRootLogin
        value: 'false'
        no_extra_spaces: true
        mode: 0444
    - name: Install the colord PolicyKit Local Authority Policy
      # see /usr/share/polkit-1/actions/org.freedesktop.color.policy
      # see pkla-check-authorization(8)
      # see xRDP How to Fix the Infamous system crash popups at http://c-nergy.be/blog/?p=12043
      # see xRDP Easy install xRDP on Ubuntu at https://c-nergy.be/blog/?p=15733
      # see xRDP installer script at https://c-nergy.be/products.html
      ansible.builtin.copy:
        src: 45-colord.pkla
        dest: /etc/polkit-1/localauthority/50-local.d/45-colord.pkla
        mode: 0400
    - name: Configure Session Variables
      # see Fixing Theme and Extensions at http://c-nergy.be/blog/?p=12043
      ansible.builtin.copy:
        dest: /etc/X11/Xsession.d/00xrdp
        content: |
          if [ -z "$XRDP_SESSION" ]; then
            return 0
          fi
          export GNOME_SHELL_SESSION_MODE=ubuntu
          export XDG_CURRENT_DESKTOP=ubuntu:GNOME
          export XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
        mode: 0444
