- name: Delegate the DNS domain {{ cluster_name + "." + cluster_domain }}
  ansible.builtin.copy:
    # set the dns server to be the cluster cidr .2 ip address.
    content: |
      server=/{{ cluster_name }}.{{ cluster_domain }}/{{ cluster.network_cidr | ansible.utils.nthhost(2) }}#30053
    dest: /etc/dnsmasq.d/{{ cluster_name }}.{{ cluster_domain }}.conf
  notify: Restart dnsmasq
