- name: Delegate {{ cluster_name }}.{{ cluster_domain }} DNS to the cluster
  copy:
    # set the dns server to be the cluster cidr .2 ip address.
    content: |
      server=/{{ cluster_name }}.{{ cluster_domain }}/{{ cluster.network_cidr | ansible.utils.nthhost(2) }}#30053
    dest: /etc/dnsmasq.d/{{ cluster_name }}.{{ cluster_domain }}.conf
  notify: restart dnsmasq
