- name: Trust the Kubernetes Ingress CA
  block:
    - name: Get Kubernetes Ingress CA
      kubernetes.core.k8s_info:
        namespace: cert-manager
        api_version: v1
        kind: Secret
        name: ingress-tls
      register: ingress_tls
    - name: Save Kubernetes Ingress CA Certificate to ~/.kube/{{ cluster_name }}-ingress-ca-crt.pem
      # see openssl x509 -text -noout -in ~/.kube/talos-ca-crt.pem
      copy:
        mode: 0444
        dest: ~/.kube/{{ cluster_name }}-ingress-ca-crt.pem
        content: '{{ ingress_tls.resources[0].data["tls.crt"] | b64decode }}'
    - name: Trust the Kubernetes Ingress CA
      nssdb_certificate:
        name: '{{ cluster_name }} Kubernetes Ingress CA'
        remote_src: ~/.kube/{{ cluster_name }}-ingress-ca-crt.pem
        trust: C,,
