- name: Install xq
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-xq.sh') }}"
  environment:
    XQ_VERSION: "{{ xq_version }}"
  register: xq_result
  changed_when: "'ANSIBLE CHANGED NO' not in xq_result.stdout_lines"
