cluster_name: k3d
cluster_domain: test
provision_username: '{{ ansible_user }}'
provision_password: '{{ ansible_password }}'

# see https://github.com/k3d-io/k3d/releases
# renovate: datasource=github-releases depName=k3d-io/k3d
k3d_version: '5.4.7'

# see https://github.com/databus23/helm-diff/releases
# renovate: datasource=github-releases depName=databus23/helm-diff
helm_diff_version: '3.6.0'

# see https://artifacthub.io/packages/helm/bitnami/metallb
# renovate: datasource=helm depName=metallb registryUrl=https://charts.bitnami.com/bitnami
metallb_chart_version: '4.1.15' # app version: 0.13.7

# see https://artifacthub.io/packages/helm/cert-manager/cert-manager
# renovate: datasource=helm depName=cert-manager registryUrl=https://charts.jetstack.io
cert_manager_chart_version: '1.11.0' # app version: 1.11.0

# see https://artifacthub.io/packages/helm/traefik/traefik
# renovate: datasource=helm depName=traefik registryUrl=https://helm.traefik.io/traefik
traefik_chart_version: '21.1.0' # app version: 2.9.7

# see https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard
# renovate: datasource=helm depName=kubernetes-dashboard registryUrl=https://kubernetes.github.io/dashboard
kubernetes_dashboard_chart_version: '6.0.0' # app version: 2.7.0

# see https://artifacthub.io/packages/helm/bitnami/external-dns
# renovate: datasource=helm depName=external-dns registryUrl=https://charts.bitnami.com/bitnami
external_dns_chart_version: '6.14.0' # app version: 0.13.2

# see https://hub.docker.com/r/powerdns/pdns-auth-47
# see https://hub.docker.com/search?q=pdns-auth-
# see https://github.com/PowerDNS/pdns/blob/master/Dockerfile-auth
# renovate: datasource=docker depName=powerdns/pdns-auth-47
pdns_version: '4.7.3' # app version: 4.7.3
