- name: Install tinygo
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-tinygo.sh') }}"
  environment:
    TINYGO_VERSION: "{{ tinygo_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Add tinygo to PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/tinygo.sh
    content: |
      export PATH="$PATH:/opt/tinygo/bin"
    mode: 0444
