# see apt-cache madison powershell
# see https://github.com/PowerShell/PowerShell/releases
# renovate: datasource=deb:microsoft depName=powershell extractVersion=^(?<version>7\.6\..+)-1\.deb$
powershell_version: '7.6.0'
