- name: Install Android SDK
  block:
    - name: Install Android SDK
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: "{{ lookup('file', 'install-android-sdk.sh') }}"
      environment:
        ANDROID_SDK_CMDLINE_TOOLS_BUILD: "{{ android_sdk_cmdline_tools_build }}"
        ANDROID_SDK_CMDLINE_TOOLS_VERSION: "{{ android_sdk_cmdline_tools_version }}"
        ANDROID_SDK_PACKAGES: "{{ android_sdk_packages | join('\n') }}"
      register: android_result
      changed_when: "'ANSIBLE CHANGED YES' in android_result.stdout_lines"
    # see https://developer.android.com/tools/variables#set
    - name: Configure Android SDK environment variables
      ansible.builtin.copy:
        content: |
          export ANDROID_HOME=/opt/android-sdk
          export PATH="$PATH:$ANDROID_HOME/cmdline-tools/{{ android_sdk_cmdline_tools_version }}/bin:$ANDROID_HOME/platform-tools"
        dest: /etc/profile.d/android-sdk.sh
        mode: 0444

# NB javac is bundled with android studio at /opt/android-studio/jbr/bin.
- name: Install Android Studio
  block:
    - name: Install Android Studio
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: "{{ lookup('file', 'install-android-studio.sh') }}"
      environment:
        ANDROID_STUDIO_VERSION: "{{ android_studio_version }}"
      register: android_result
      changed_when: "'ANSIBLE CHANGED NO' not in android_result.stdout_lines"
    - name: Install android-studio symlink
      ansible.builtin.file:
        src: /opt/android-studio/bin/studio
        dest: /usr/local/bin/android-studio
        force: true
        state: link
    - name: Create system local applications directory
      ansible.builtin.file:
        name: /usr/local/share/applications
        state: directory
        mode: 0755
    - name: Install Android Studio desktop file
      ansible.builtin.copy:
        src: android-studio.desktop
        dest: /usr/local/share/applications
        mode: 0444
