- name: Install cfssl
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-cfssl.sh') }}"
  environment:
    CFSSL_VERSION: "{{ cfssl_version }}"
  register: cfssl_result
  changed_when: "'ANSIBLE CHANGED NO' not in cfssl_result.stdout_lines"
