- name: Download the nodesource apt key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/deb.nodesource.com.asc
    mode: 0444
    force: true

- name: Add the nodesource apt repository
  ansible.builtin.apt_repository:
    # see https://wiki.debian.org/DebianRepository/Format
    # see node 20.x: https://deb.nodesource.com/node_20.x/dists/nodistro/Release
    # see node 20.x: https://deb.nodesource.com/node_20.x/dists/nodistro/main/binary-amd64/Packages
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/deb.nodesource.com.asc]
      https://deb.nodesource.com/node_{{ nodejs_version.split('.')[0] }}.x
      nodistro
      main
    state: present

# see https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
# NB execute apt-cache madison nodejs to known the available versions.
- name: Install nodejs
  block:
    - name: Install nodejs
      ansible.builtin.apt:
        name: nodejs={{ nodejs_version }}-*
        allow_change_held_packages: true
        state: present
    - name: Pin nodejs
      ansible.builtin.dpkg_selections:
        name: nodejs
        selection: hold

- name: Install node bash completion
  block:
    - name: Get node bash completion
      ansible.builtin.command: node --completion-bash
      register: nodejs_node_bash_completion
      changed_when: false
    - name: Install node bash completion
      ansible.builtin.copy:
        content: "{{ nodejs_node_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/node
        mode: 0444

- name: Install npm bash completion
  block:
    - name: Get npm bash completion
      ansible.builtin.command: npm completion
      register: nodejs_npm_bash_completion
      changed_when: false
    - name: Install npm bash completion
      ansible.builtin.copy:
        content: "{{ nodejs_npm_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/npm
        mode: 0444
