# provision cert-manager.
# NB YOU CANNOT INSTALL MULTIPLE INSTANCES OF CERT-MANAGER IN A CLUSTER.
# see https://artifacthub.io/packages/helm/cert-manager/cert-manager
# see https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
# see https://cert-manager.io/docs/installation/supported-releases/
# see https://cert-manager.io/docs/configuration/selfsigned/#bootstrapping-ca-issuers
# see https://cert-manager.io/docs/usage/ingress/

- name: Add jetstack repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: '{{ cert_manager_chart_version }}'
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    values:
      # NB installCRDs is generally not recommended, BUT since this
      #    is a development cluster we YOLO it.
      installCRDs: true

- name: Create selfsigned ClusterIssuer
  kubernetes.core.k8s:
    definition:
      # see https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.ClusterIssuer
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned
      spec:
        selfSigned: {}

- name: Create Kubernetes Ingress CA Certificate
  kubernetes.core.k8s:
    definition:
      # see https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: ingress
        namespace: cert-manager
      spec:
        isCA: true
        subject:
          organizations:
            - '{{ cluster_name }}.{{ cluster_domain }}'
          organizationalUnits:
            - Kubernetes
        commonName: Kubernetes Ingress
        privateKey:
          algorithm: ECDSA # NB Ed25519 is not yet supported by chrome 93 or firefox 91.
          size: 256
        duration: 4320h # NB 4320h (180 days). default is 2160h (90 days).
        secretName: ingress-tls
        issuerRef:
          name: selfsigned
          kind: ClusterIssuer
          group: cert-manager.io

- name: Create Kubernetes Ingress CA ClusterIssuer
  kubernetes.core.k8s:
    definition:
      # see https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.ClusterIssuer
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: ingress
      spec:
        ca:
          secretName: ingress-tls
