- name: Install k3d
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-k3d.sh') }}"
  environment:
    K3D_VERSION: "{{ k3d_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Install k3d bash completion
  block:
    - name: Get k3d bash completion
      ansible.builtin.command: k3d completion bash
      register: bash_completion
      changed_when: false
    - name: Install k3d bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/k3d
        mode: 0444
