# see https://artifacthub.io/packages/helm/bitnami/metallb
# see https://metallb.universe.tf/configuration/#layer-2-configuration
# see https://github.com/bitnami/charts/tree/master/bitnami/metallb
# see https://kind.sigs.k8s.io/docs/user/loadbalancer/

- name: Add bitnami repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Install metallb
  kubernetes.core.helm:
    name: kube-metallb
    chart_ref: bitnami/metallb
    chart_version: '{{ metallb_chart_version }}'
    release_namespace: kube-metallb
    create_namespace: true
    update_repo_cache: true
    values:
      speaker:
        secretValue: abracadabra # TODO use a proper secret.

- name: Configure metallb
  kubernetes.core.k8s:
    namespace: kube-metallb
    definition:
      - apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: default
        spec:
          addresses:
            # use the last 54 addresses from the assigned network. e.g. with
            # a network of 172.18/16 use 172.18.255.200-172.18.255.254.
            - '{{ cluster.network_cidr | ansible.utils.nthhost(-(54+2)) }}-{{ cluster.network_cidr | ansible.utils.nthhost(-2) }}'
      - apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: default
  register: result
  # NB we have to retry until the metallb-webhook-service endpoint is
  #    available. while its starting, it will fail with:
  #       Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post
  #       "https://metallb-webhook-service.kube-metallb.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": dial tcp
  #       10.96.9.119:443: connect: connection refused
  #    see https://github.com/metallb/metallb/issues/1597
  until: result is succeeded
  retries: 10
  delay: 5
