# see https://github.com/moby/moby/releases
# renovate: datasource=deb:docker depName=docker-ce
docker_version: '29.8.0'

# see https://github.com/containerd/containerd/releases
# renovate: datasource=deb:docker depName=containerd.io
docker_containerd_version: '2.3.5'

# see https://github.com/docker/compose/releases
# renovate: datasource=github-releases depName=docker/compose
docker_compose_version: '5.5.1'
