- name: Install grype
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-grype.sh') }}"
  environment:
    GRYPE_VERSION: "{{ grype_version }}"
  register: grype_result
  changed_when: "'ANSIBLE CHANGED NO' not in grype_result.stdout_lines"

- name: Install grype bash completion
  block:
    - name: Get grype bash completion
      ansible.builtin.command: grype completion bash
      register: grype_bash_completion
      changed_when: false
    - name: Install grype bash completion
      ansible.builtin.copy:
        content: "{{ grype_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/grype
        mode: 0444
