# see https://github.com/rgl/lms-binaries/releases
# renovate: datasource=github-releases depName=rgl/lms-binaries
lms_binaries_version: 'v0.0.20230801'

# NB this must exist in https://github.com/rgl/lms-binaries/releases.
# see https://github.com/intel/lms/releases
# renovate: datasource=github-releases depName=intel/lms
lms_version: '2322.0.0'
