- name: Install javy
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-javy.sh') }}"
  environment:
    JAVY_VERSION: "{{ javy_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
