# see https://dotnet.microsoft.com/en-us/download/dotnet/6.0
# see https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
# renovate: datasource=dotnet depName=dotnet-sdk extractVersion=^(?<version>6\..+)
dotnet_sdk_6_version: '6.0.422' # dotnet 6.0.30

# see https://dotnet.microsoft.com/en-us/download/dotnet/8.0
# see https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
# renovate: datasource=dotnet depName=dotnet-sdk
dotnet_sdk_8_version: '8.0.204' # dotnet 8.0.4

dotnet_sdk_versions:
  - '{{ dotnet_sdk_6_version }}'
  - '{{ dotnet_sdk_8_version }}'
