- name: Install dagger
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install.sh') }}"
  environment:
    DAGGER_VERSION: "{{ dagger_version }}"
  register: dagger_result
  changed_when: "'ANSIBLE CHANGED NO' not in dagger_result.stdout_lines"

- name: Install dagger bash completion
  block:
    - name: Get dagger bash completion
      ansible.builtin.command: dagger completion bash
      register: dagger_bash_completion
      changed_when: false
    - name: Install dagger bash completion
      ansible.builtin.copy:
        content: "{{ dagger_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/dagger
        mode: 0444
