- name: Install syft
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-syft.sh') }}"
  environment:
    SYFT_VERSION: "{{ syft_version }}"
  register: syft_result
  changed_when: "'ANSIBLE CHANGED NO' not in syft_result.stdout_lines"

- name: Install syft bash completion
  block:
    - name: Get syft bash completion
      ansible.builtin.command: syft completion bash
      register: syft_bash_completion
      changed_when: false
    - name: Install syft bash completion
      ansible.builtin.copy:
        content: "{{ syft_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/syft
        mode: 0444
