dns_servers:
  # delegate to the Cloudflare/APNIC Public DNS IP addresses.
  # see https://1.1.1.1
  - 1.1.1.1
  - 1.0.0.1
  # delegate to the Google Public DNS IP addresses.
  # see https://8.8.8.8
  #- 8.8.8.8
  #- 8.8.4.4
