- name: Install go
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-go.sh') }}"
  environment:
    GO_VERSION: "{{ go_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Add go to PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/go.sh
    content: |
      export PATH="$PATH:/opt/go/bin"
      export PATH="$PATH:$HOME/go/bin"
