- name: Install wasmer dependencies
  ansible.builtin.apt:
    name: libtinfo5

- name: Install wasmer
  become_user: '{{ ansible_user }}'
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-wasmer.sh') }}"
  environment:
    WASMER_VERSION: "{{ wasmer_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
