- name: Install aws
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-aws.sh') }}"
  environment:
    AWS_VERSION: "{{ aws_client_aws_version }}"
  register: aws_client_result
  changed_when: "'ANSIBLE CHANGED NO' not in aws_client_result.stdout_lines"

- name: Install aws bash completion
  ansible.builtin.copy:
    # see https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-completion.html#cli-command-completion-linux
    content: |
      complete -C /usr/local/bin/aws_completer aws
    dest: /usr/share/bash-completion/completions/aws
    mode: 0444

- name: Uninstall old aws versions
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'uninstall-aws.sh') }}"
  environment:
    AWS_VERSION: "{{ aws_client_aws_version }}"
  register: aws_client_result
  changed_when: "'ANSIBLE CHANGED NO' not in aws_client_result.stdout_lines"

- name: Install aws session manager plugin
  block:
    - name: Check aws session manager plugin installed version
      ansible.builtin.command: dpkg-query -W -f='${Version}' session-manager-plugin
      register: aws_client_session_manager_plugin_info
      failed_when: false
      changed_when: false
    - name: Install aws ssm plugin
      ansible.builtin.apt:
        deb: https://s3.amazonaws.com/session-manager-downloads/plugin/{{ aws_client_session_manager_plugin_version }}/ubuntu_64bit/session-manager-plugin.deb
      when: >
        (aws_client_session_manager_plugin_info.stdout
          | regex_replace('^[0-9]+:', '')
          | regex_replace('~.*$', '')
          | regex_replace('-[^-]+$', ''))
        != aws_client_session_manager_plugin_version
