- name: Install git
  block:
    - name: Install git
      ansible.builtin.apt:
        name: git
        install_recommends: false
    - name: Install gitconfig
      ansible.builtin.copy:
        src: gitconfig
        dest: /etc/gitconfig
        mode: 0444
    - name: Create gitconfig.d directory
      ansible.builtin.file:
        name: /etc/gitconfig.d
        state: directory
        mode: 0755
