- name: Install cilium
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-cilium.sh') }}"
  environment:
    CILIUM_VERSION: "{{ k8s_client_cilium_version }}"
  register: k8s_client_result
  changed_when: "'ANSIBLE CHANGED NO' not in k8s_client_result.stdout_lines"

- name: Install cilium bash completion
  block:
    - name: Get cilium bash completion
      ansible.builtin.command: cilium completion bash
      register: k8s_client_bash_completion
      changed_when: false
    - name: Install cilium bash completion
      ansible.builtin.copy:
        content: "{{ k8s_client_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/cilium
        mode: 0444
