- name: Install crane
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-crane.sh') }}"
  environment:
    CRANE_VERSION: "{{ k8s_client_crane_version }}"
  register: k8s_client_result
  changed_when: "'ANSIBLE CHANGED NO' not in k8s_client_result.stdout_lines"

- name: Install crane bash completion
  block:
    - name: Get crane bash completion
      ansible.builtin.command: "crane completion bash"
      register: k8s_client_bash_completion
      changed_when: false
    - name: Install crane bash completion
      ansible.builtin.copy:
        content: "{{ k8s_client_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/crane
        mode: 0444
