- name: Install kubectl
  ansible.builtin.include_tasks: kubectl.yml

- name: Install k9s
  ansible.builtin.include_tasks: k9s.yml

- name: Install Helm
  ansible.builtin.include_tasks: helm.yml

- name: Install ORAS
  ansible.builtin.include_tasks: oras.yml

- name: Install Skopeo
  ansible.builtin.include_tasks: skopeo.yml

- name: Install Crane
  ansible.builtin.include_tasks: crane.yml

- name: Install regclient
  ansible.builtin.include_tasks: regclient.yml
  loop:
    - regctl
    - regsync

- name: Install cmctl
  ansible.builtin.include_tasks: cmctl.yml

- name: Install cilium
  ansible.builtin.include_tasks: cilium.yml

- name: Install hubble
  ansible.builtin.include_tasks: hubble.yml
