- name: Install ORAS
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-oras.sh') }}"
  environment:
    ORAS_VERSION: "{{ oras_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Install ORAS bash completion
  block:
    - name: Get ORAS bash completion
      ansible.builtin.command: "oras completion bash"
      register: bash_completion
      changed_when: false
    - name: Install ORAS bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/oras
        mode: 0444
