- name: Install ORAS
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-oras.sh') }}"
  environment:
    ORAS_VERSION: "{{ k8s_client_oras_version }}"
  register: k8s_client_result
  changed_when: "'ANSIBLE CHANGED NO' not in k8s_client_result.stdout_lines"

- name: Install ORAS bash completion
  block:
    - name: Get ORAS bash completion
      ansible.builtin.command: "oras completion bash"
      register: k8s_client_bash_completion
      changed_when: false
    - name: Install ORAS bash completion
      ansible.builtin.copy:
        content: "{{ k8s_client_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/oras
        mode: 0444
