- name: Install {{ item }}
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-regclient.sh') }}"
  environment:
    REGCLIENT_NAME: "{{ item }}"
    REGCLIENT_VERSION: "{{ k8s_client_regclient_version }}"
  register: k8s_client_result
  changed_when: "'ANSIBLE CHANGED NO' not in k8s_client_result.stdout_lines"

- name: Install bash completion for  {{ item }}
  block:
    - name: Get bash completion for {{ item }}
      ansible.builtin.command: "{{ item }} completion bash"
      register: k8s_client_bash_completion
      changed_when: false
    - name: Install bash completion for {{ item }}
      ansible.builtin.copy:
        content: "{{ k8s_client_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/{{ item }}
        mode: 0444
