- name: Install timoni
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-timoni.sh') }}"
  environment:
    TIMONI_VERSION: "{{ k8s_client_timoni_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Install timoni bash completion
  block:
    - name: Get timoni bash completion
      ansible.builtin.command: timoni completion bash
      register: bash_completion
      changed_when: false
    - name: Install timoni bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/timoni
        mode: 0444
