- name: Install timoni
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-timoni.sh') }}"
  environment:
    TIMONI_VERSION: "{{ k8s_client_timoni_version }}"
  register: k8s_client_result
  changed_when: "'ANSIBLE CHANGED NO' not in k8s_client_result.stdout_lines"

- name: Install timoni bash completion
  block:
    - name: Get timoni bash completion
      ansible.builtin.command: timoni completion bash
      register: k8s_client_bash_completion
      changed_when: false
    - name: Install timoni bash completion
      ansible.builtin.copy:
        content: "{{ k8s_client_bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/timoni
        mode: 0444
