- name: Install solo2
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-solo2.sh') }}"
  environment:
    SOLO2_VERSION: "{{ solo2_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"
