- name: Install wasmtime
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-wasmtime.sh') }}"
  environment:
    WASMTIME_VERSION: "{{ wasmtime_version }}"
  register: wasmtime_result
  changed_when: "'ANSIBLE CHANGED NO' not in wasmtime_result.stdout_lines"

- name: Install wasm-tools
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-wasm-tools.sh') }}"
  environment:
    WASM_TOOLS_VERSION: "{{ wasmtime_wasm_tools_version }}"
  register: wasmtime_result
  changed_when: "'ANSIBLE CHANGED NO' not in wasmtime_result.stdout_lines"
