# see https://bun.sh/docs/runtime/configuration#environment-variables
- name: Opt-out of telemetry
  ansible.builtin.copy:
    content: |
      export DO_NOT_TRACK=1
    dest: /etc/profile.d/opt-out-bun-telemetry.sh
    mode: 0444

- name: Install bun
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-bun.sh') }}"
  environment:
    BUN_VERSION: "{{ bun_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Install bun bash completion
  block:
    - name: Get bun bash completion
      ansible.builtin.command: bun completions bash
      register: bash_completion
      changed_when: false
    - name: Install bun bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/bun
        mode: 0444
